### ISSUE TITLE
Missing dependency in docs

### ISSUE THREAD

**Issue by robc-io** [icon-project/preptools#11]
There is a dependency that is missing in the docs.  For ubuntu installations you need `apt get libsecp256k1-dev`. 

People in the telegram are also struggling with basic venv installation stuff so can you update the docs to include the pip install method off of pypi now that it is up there. 

I can do PR if needed. 

Thanks for the tool!

**Comment by robc-io** [comment]
This is what helped one of the members of the community get going with this. 
```bash
sudo apt-get install libssl-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev libyaml-cpp-dev
sudo apt-get install python3.7-dev libsecp256k1-dev python3-pip 
sudo pip3 install preptools
```

**Comment by goldworm-icon** [comment]
I'll add the dependencies that you mentioned to the document.
Thank you for your interest on ICON.
