### ISSUE TITLE
Need default flag for step limit 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/preptools#29]
Don't know if it was the release or an update to the API but transactions now require posting a step limit flag. 

Running `preptools setPRep ....` with the `--node-address` registering a dualized keystore throws this error.  I mention the dualized keystore as this transaction typically requires a few ICX to execute. 

Error: `Transaction should have step limit when signed. (Data type **error)**`

Adding default to step price fixes this for the prep commands.  Submitted PR [#30](https://github.com/icon-project/preptools/pull/30) with test.

**Comment by inwonkim** [comment]
Thank you for report.
In  [#30](https://github.com/icon-project/preptools/pull/30) a unit test failed. so, did not merge. As [#34](https://github.com/icon-project/preptools/pull/34) merged, I confirmed that the test passed and merged [#30](https://github.com/icon-project/preptools/pull/30)

**Comment by robcxyz** [comment]
Hasn't been an issue lately so closing.
