### ISSUE TITLE
Missing import from iconsdk.utils.convert_type.py

### ISSUE THREAD

**Issue by benjaminvanseggelen** [icon-project/preptools#33]
The file `preptools/command/proposal_settings_command.py` currently imports the function: `convert_params_value_to_hex_str` from `iconsdk.utils.convert_type.py`.

This function was removed from the icon sdk in [this commit](https://github.com/icon-project/icon-sdk-python/commit/003b8dbe86567f985543fda9f42aa49f7c3948c1#diff-f3a94148a1525bb7ade6c27479863caa666cb4cc1b6a641f86b35e7d88721136).

Because of this, preptools will not run with the newest version of the icon sdk.

Using `object_to_str` from `iconsdk.utils.typing.conversion` instead fixed this locally for me. However, I am not sure whether this could cause issues somewhere else.

**Comment by ICONationDevTeam** [comment]
[Multiple people](https://t.me/icondevs/14401) had the same issue as well.
A known workaround is to downgrade iconsdk to the version 1.3.1. 

@benjaminvanseggelen your patch sounds good to me, replacing `convert_params_value_to_hex_str` with `object_to_str` shouldn't change the preptool behavior.

**Comment by benjaminvanseggelen** [comment]
Thank you for the quick response! I have created the pull request.
As noted in the PR, I am new to preptools, so I trust you to be able to verify whether this does not break something else :)
