### ISSUE TITLE
improve unresgister p-rep command documents

### ISSUE THREAD

**Issue by fireagainsmile** [icon-project/preptools#35]
unregister a p-rep is not stressing about the icx that is used to register a p-rep.
this is something really important we should make it clear to all the users.
current unregister command does is not clear, users DO NOT know what they are doing just according the description.

I unregistered my p-rep and lost 2k icx by mistake when I follow the unregister p-rep steps.

**Comment by inwonkim** [comment]
Thank you for feedback.
We released new version!

**Comment by fireagainsmile** [comment]
I want to be reasonable, don't make me feel upset.

This is definitely a misleading description of unregister p-rep from ICON.
Who is going to be responsible for this mistake? and no one is answering my question in several telegram community.
If it is still not solved here, I'm afraid I have to open more issues using github tools until someone tell me who is responsible for this loss.

**Comment by ICONationDevTeam** [comment]
@fireagainsmile I feel sorry, but you are entirely responsible of your funds. The mistake you're talking about is about thinking any fee would be refundable by default. How does it make sense ? That's like saying transaction fees or exchange withdraw fees should be refundable too... 

If you want to improve this situation, is there anything in the documentation that made you think the fee was going to be refunded ?

**Comment by fireagainsmile** [comment]
yes of course, In the unregister p-rep, the value is zero. to a user he would think that if he set the value to zero, then I could be zero registered, without saying anything about how the tokens change or the p-rep status changes, it is misleading the user that the register fee maybe going to fund back.

Many companies in my country, the register fee is withdrawable, if IT IS NOT, they would stress that with the highlighted font, It is very important when coming to money, it is the very first information should let the users knew.
besides that, why should we let the users do the unregister, since there is no benefit to the p-rep user like the community members say, you are allowing p-rep doing some misbehaviours according to the misleading instruction.

I am not the only one who doesn't know this before,  several active community members told me they are not aware of this either.

**Comment by fireagainsmile** [comment]
no responding Again ??

**Comment by ICONationDevTeam** [comment]
So let me sum it up.

You made assumptions based on your experience and interpreted the documentation the way you want, and concluded "the fee is refundable". You think you deserve 2000 ICX to be sent back to you.

Without saying if you're right or wrong : who do you think will pay for that ?
Your ICX are burnt, which means someone else would need to pay for your mistake.
Could you first clarify who are you asking these ICX for ? 
The document writer ? The ICON Foundation ? The ICON community ? Who ever you picked, why do you think they should be held responsible for your loss ?

I'm a community member just like you are by the way. Don't expect too much.

**Comment by fireagainsmile** [comment]
> So let me sum it up.
> 
> You made assumptions based on your experience and interpreted the documentation the way you want, and concluded "the fee is refundable". You think you deserve 2000 ICX to be sent back to you.
yeah, me think. how about let's say, IT IS the document description is making users thought that way. no me, me.
> 
> Without saying if you're right or wrong : who do you think will pay for that ?
> Your ICX are burnt, which means someone else would need to pay for your mistake.
> Could you first clarify who are you asking these ICX from ?
> The documentation writer ? The ICON Foundation ? The ICON community ? Whoever you picked, why do you think they should be held responsible for your loss ? Please note that even if you misinterpreted the documentation, you, and only you, are fully responsible of your funds and what you do with it. This is all what crypto is about.
> 

so F ridiculous. The users supporting the team with money, but you guys released so ridiculous specifications.
Based on your response, I was wondering if you are a qualified member of the team.

> I'm a community member just like you are by the way. Don't expect too much from me.
> I'm really sorry you lost funds. But I think you did everything possible, that is to prevent someone else from doing the same mistake than you did. [That warning](https://github.com/icon-project/preptools/commit/f3cb3ddcd6937f7d20ad1787ab4278644176d836) should be good enough.

At Least, please, take a look at the TIMESTAMP of that commit. ok?

**Comment by ICONationDevTeam** [comment]
>  Based on your response, I was wondering if you are a qualified member of the team.

I'm not a member of the ICON team.

> At Least, please, take a look at the TIMESTAMP of that commit. ok?

You didn't read my answer correctly either.

I got nothing more to say on that issue, we're both wasting time here.

**Comment by fireagainsmile** [comment]
> > yeah, me think. how about let's say, IT IS the document description is making users thought that way. no me, me, me.
> 
> You're the first one on more than a hundred of P-Rep that did that mistake. How is that possible none else thinks the same you do if the documentation says it's refundable ?

huh??? what do you want to say? 
maybe I am the first one who is doing the  rediculous unregister p-rep instructions, ACCORDING TO the documents !!
> 
> > Based on your response, I was wondering if you are a qualified member of the team.
> 
> I'm not a member of the ICON team.

you are using the official  github accout! stop play with me.  and stop saying irresponsible words!!
> 
> > At Least, please, take a look at the TIMESTAMP of that commit. ok?
> 
> You didn't read my answer correctly either.
> 
> I got nothing more to say on that issue, we're both wasting time here.

if you are not going to do something on this, then I will wast my own time until somebody can!

**Comment by fireagainsmile** [comment]
what is the matter with this develop team???

**Comment by fireagainsmile** [comment]
what is wrong with this team!
