### ISSUE TITLE
setPrep returning invalid Tx hash

### ISSUE THREAD

**Issue by robcxyz** [icon-project/preptools#36]
After running setPrep, with this command: 

```
preptools setPRep --config preptools_config.json --node-address OMIT --prep-json registerPRep.json --step-limit 0x5000000000
```

I get a response indicative of a successful transaction:

```
txHash : {'jsonrpc': '2.0', 'result': '0x0ee914ed4c368d833974cde4ea307d39ad2d67c719ba934cb0b7e02db1c47d79', 'id': 1234}
```

But the transaction doesn't exist.  Using this preptools_config,json

```
{
   "url": "https://ctz.solidwallet.io/api/v3",
   "nid": 1,
   "keystore": OMIT
}
```

**Comment by inwonkim** [comment]
Would you show me your **registerPRep.json** contents?

**Comment by robcxyz** [comment]
This has been resolved.  Error was not giving warning when wallet does not have sufficient balance.  Error is returned on newer version so consider this closed.
