### ISSUE TITLE
Ambiguous error from setPRep 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/preptools#37]
Per title, getting ambiguous error with setPRep. 

```
preptools setPRep --config preptools_config.json --node-address hxNODE_ADDRESS --prep-json registerPRep.json
{'code': -30006, 'message': 'SystemError(-30006) : E0006:Failed to set PRep: from=hxPREP_ADDRESS'}
```

This worked recently.  Using preptools v1.2.3 and tested down to v1.2.0 so thinking this is in iconsdk as the error doesn't seem to  come from preptools itself.

**Comment by goldworm-icon** [comment]
The error message comes from an icon node
If you share registerPRep.json or let me know its tx_hash, It will be very helpful to find out its cause.

Anyway, it seems that you want to change your node_address according to the command above.
There are some reasons to make an failure of setPRep.
I'm not sure but if you try to reuse the node address which has already been set before, it can cause the failure like that.

**Comment by robcxyz** [comment]
@goldworm-icon - Thank you for the quick reply.  

Indeed it was a node address that had been used before.  Closing issue as it is now working.
